#!/bin/bash

# Project: Digibee Git Sync
# Written by: Artur Scheiner
# Email: artur.scheiner@gmail.com

#Global Variables
# Absolute path to this script, e.g. /home/user/bin/foo.sh
THIS_SCRIPT=$(readlink -f "$0")

# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$THIS_SCRIPT")

# This script name
ME="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

# Define the installation type local folder or system wide
isLocal()[[ $0 == ./* ]]
isLocal && THIS_TYPE="$0" || THIS_TYPE="$ME"

modelPath="$SCRIPTPATH/model"
interpreterPath="$SCRIPTPATH/model/interpreters"
templatesPath="$SCRIPTPATH/model/templates"
viewPath="$SCRIPTPATH/view"
controllerPath="$SCRIPTPATH/control"
filtersPath="$modelPath/filters"
tempPath="/tmp/$ME"

MAJOR_VERSION="0"
MINOR_VERSION="2"
HASH_VERSION=$(cat $THIS_SCRIPT $modelPath/* $controllerPath/* $viewPath/* | shasum | awk '{print substr($1,0,5)}')
HVERSION="v$MAJOR_VERSION.$MINOR_VERSION.$HASH_VERSION"

for m in $(ls $modelPath); do [ ! -d $modelPath/$m ] && . $modelPath/$m; done
for v in $(ls $viewPath); do [ ! -d $viewPath/$v ] && . $viewPath/$v; done
for c in $(ls $controllerPath); do [ ! -d $controllerPath/$c ] && . $controllerPath/$c; done

############################################################
# Init Program                                             #
############################################################
showViewHeader
#SetEnvironmentData

if CheckRequirements $1; then
    initControlMain $1
    initViewMain "$@"
else
    initViewError
fi