#!/bin/bash

# This script name
DENOMINATOR="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

POSITION=$1
ID=$2
templatesPath=$3
documentationPath=$4
tempPath=$5

OBJECTSPEC=$tempPath/$ID.json

jq -r '. | .template' $OBJECTSPEC > $tempPath/$ID-TEMPLATE.txt

STEPNAME=$(jq -r '.stepName' $OBJECTSPEC)
MODELPATH=$(jq -r '. | .modelPath' $OBJECTSPEC)
PRESERVEORIGINAL=$(jq -r '. | .preserveOriginal' $OBJECTSPEC)
TEMPLATE=$tempPath/$ID-TEMPLATE.txt

DOCUMENTATION=$(jq -r '.__documentation__' $OBJECTSPEC)

if [[ "$DOCUMENTATION" == "null" ]]; then
     DOCUMENTATION="O parâmetro referente à documentação descritiva do componente não foi preenchido ou está indisponível para este componente." 
fi

sed "s/--STEPNAME--/$STEPNAME/g;\
     s/--DENOMINATOR--/$DENOMINATOR/g;\
     s/--DOCUMENTATION--/$DOCUMENTATION/g;\
     s/--MODELPATH--/$MODELPATH/g; \
     s/--PRESERVEORIGINAL--/$PRESERVEORIGINAL/g; \
     /--TEMPLATE--/r $TEMPLATE" \
     $templatesPath/$DENOMINATOR.md | \
sed "/--RAWOBJECT--/r $OBJECTSPEC" | \
sed "/--RAWOBJECT--/d;/--TEMPLATE--/d"