#!/bin/bash

# This script name
DENOMINATOR="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"

POSITION=$1
ID=$2
templatesPath=$3
documentationPath=$4
tempPath=$5

OBJECTSPEC=$tempPath/$ID.json

jq '. | .transformSpec' $tempPath/$ID.json > $tempPath/$ID-TRANSFORMSPEC.json

TRANSFORMSPEC=$tempPath/$ID-TRANSFORMSPEC.json
STEPNAME=$(cat $OBJECTSPEC | jq -r '.stepName' | sed 's/\//_/g')
FAILONERROR=$(cat $OBJECTSPEC | jq '.params | .failOnError')
FIVEID=$(echo ${ID:0:5})

DOCUMENTATION=$(jq -r '.__documentation__' $OBJECTSPEC)

if [[ "$DOCUMENTATION" == "null" ]]; then
     DOCUMENTATION="O parâmetro referente à documentação descritiva do componente não foi preenchido ou está indisponível para este componente." 
fi

sed "s/--STEPNAME--/$STEPNAME/g;\
     s/--DENOMINATOR--/$DENOMINATOR/g;\
     s/--DOCUMENTATION--/$DOCUMENTATION/g;\
     /--JOLTCODE--/r $TRANSFORMSPEC" \
     $templatesPath/$DENOMINATOR.md | \
sed "/--RAWOBJECT--/r $OBJECTSPEC" | \
sed "/--RAWOBJECT--/d;/--JOLTCODE--/d"